### ISSUE TITLE
在最新的ha上不可用

### ISSUE THREAD

**Issue by GaryOAO** [fireinice/dnspod_ha#2]
最新的ha弃用了http_ok，需要进行修改，在修改后依然无法正确连接dnspod，log如下

```
2023-12-01 23:08:49.079 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/hassio/http.py", line 180, in _handle
await response.prepare(request)
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
return await self._start(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
await self._write_headers()
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
await writer.write_headers(status_line, self._headers)
File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
self._write(buf)
File "/usr/local/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-12-01 23:09:44.373 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hassio
2023-12-01 23:10:43.866 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Supervisor for hassio
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 632, in async_setup_entry
await coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in async_config_entry_first_refresh
await self._async_refresh(
File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 1005, in _async_refresh
await self.hassio.refresh_updates()
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 37, in _wrapper
data = await funct(*argv, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 561, in send_command
request = await self.websession.request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
await resp.start(conn)
File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
message, payload = await protocol.read() # type: ignore[union-attr]
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
await self._waiter
asyncio.exceptions.CancelledError: Global task timeout
2023-12-01 23:10:43.909 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 1 - moving forward
2023-12-01 23:10:45.564 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hassio, tag, application_credentials, input_select, tts, uptime, schedule, input_boolean, logbook, switch_as_x, counter, system_health, timer, input_datetime, input_number, sun, media_source, zone, scene, input_text, hardware, xiaomi_gateway3, input_button, met
```

**Comment by fireinice** [comment]
代码做了些更改，可以先试一下是否解决问题。
只看日志看起来像是连接问题，如果重复出现，请提供一下home assistant 的版本号，运行环境。

**Comment by fireinice** [comment]
最新的release试着修复这些问题，可以再试一下，如果还有问题，可以随时打开个这个问题
